from .get_document import service_get_document
from .new_document import service_new_document
from .update_document import service_update_document
from .update_document_title import service_update_document_title
from .delete_document import service_delete_document
